drop table tb_instrument if exists;
drop table tb_order if exists;

create table tb_instrument (id BIGINT generated by default as identity, primary key (id));
create table tb_order (cl_orderid varchar(255) not null, order_type char(1), status varchar(255), primary key (cl_orderid));
