server:
  port: 8090

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true