spring:
  application:
    name: order-service
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      notify-new-order:
        maxRetryAttempts: 2
        waitDuration: 2s
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      notify-new-order:
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 1

